// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleTodo.Data;

namespace simpleTodo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SimpleTodo.Models.Todo", b =>
                {
                    b.Property<int>("todoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("todoDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("todoDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("todoTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("todoId");

                    b.ToTable("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
